### ISSUE TITLE
Add spatial and time information (x,y,z,t)

### ISSUE THREAD

**Issue by devoworm** [devoworm/GSOC-2018#38]

**Comment by arnab1896** [comment]
Work on the time slice approach for creating the *.gml files instead of one single *.gml file at the end.

It will help user understand the actual evolution over the generations.

**Comment by arnab1896** [comment]
Check screenshot taken for gml files

**Comment by devoworm** [comment]
Needs to be integrated properly.

**Comment by arnab1896** [comment]
Current step taken is finding the dividing ratio based on lowest count
