### ISSUE TITLE
Build a Codelet (feel for project)

### ISSUE THREAD

**Issue by devoworm** [devoworm/GSOC-2018#8]

**Comment by arnab1896** [comment]
https://github.com/arnab1896/GSOC-2018/tree/issue_8_codelet/python_codelet

this is where the progress of this issue can be tracked!
It's still in progress. Some work left to be done :tada:

**Comment by devoworm** [comment]
Discussed difference between developmental and differentiated cells.

**Comment by devoworm** [comment]
Discussed details of dataset.
